name: build-kernel
on:
  workflow_dispatch:
jobs:
  build-ksu:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      #- name: Setup build environment
      #  run: curl https://raw.githubusercontent.com/akhilnarang/scripts/master/setup/android_build_env.sh | bash -
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git ccache pngcrush schedtool maven lib32ncurses5-dev xsltproc libxml2-utils squashfs-tools lzop flex build-essential bc libssl-dev libswitch-perl libxml-simple-perl zip unzip g++-multilib bison gperf zlib1g-dev automake device-tree-compiler
          sudo curl --create-dirs -o /usr/local/bin/repo -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
      - name: Set Zip filename variable
        id: zipname
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-8)
          echo "zipfile="AOSPA_marble_KernelSU-Next-SUSFS_$(date +%Y%m%d_%H%M%S)_anykernel3_$COMMIT_HASH.zip"" >> "$GITHUB_OUTPUT"
      - name: Clone repo and sync
        run: |
          repo init -u https://github.com/tiltshiftfocus/kernel_manifest -b vauxite-next-susfs --depth=1
          repo sync
          mkdir -p kernel_platform/device/xiaomi/marble-kernel/dtbs
      - name: Build kernel
        run: |
          cd kernel_platform/xiaomi/sm8450
          ./build.sh --ksu marble
      - name: Zip output
        run: |
          cp kernel_platform/device/xiaomi/marble-kernel/Image AnyKernel3
          cd AnyKernel3
          rm -r .git README.md
          find . -type f -name 'placeholder' -delete
          find . -type d -empty -delete
          zip -r9 "../${{ steps.zipname.outputs.zipfile }}" *
      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ steps.zipname.outputs.zipfile }}"
      - name: Upload marble-kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: marble-kernel
          path: AnyKernel3/*
